FROM node:22.13.1-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
EXPOSE 4200

CMD ["npm", "run", "start"]

# Contruir la imagen
#> docker build -f Dockerfile-dev -t test-app-frontend .

# Crear y arrancar el contenedor
#> docker run -d -p 4200:4200 --name test-app-frontend-app test-app-frontend

# Arrancar el contenedor
#> docker start test-app-frontend-app


