name: CI
on:
  push:
    branches:
      - develop
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with: {fetch-depth: 0}
      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
      - name: Install dependencies
        run: npm ci
      - name: Build Angular App
        run: npm run-script build-prod  # package.json -> "scripts"
      - name: Tests
        run: npm run-script test-ci  # package.json -> "scripts"
      - name: SonarCloud Scan
        if: success()
        uses: SonarSource/sonarcloud-github-action@master # file: sonar-project.properties
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
